// This file is auto-generated by scripts/generate-logger-toggle-defaults.ts.
// Run `bun run generate:logger-toggles` to refresh it.

import { flattenTree, type LoggerToggleTree } from './flattenToggleTree'

const LOGGER_TOGGLE_TREE = {
	app: false,
	'code-editor': {
		$self: false,
		clipboard: false,
		history: false
	},
	desktop: false,
	fs: false,
	server: false,
	web: {
		$self: false,
		focus: false,
		LocalDirectoryFallback: false,
		prefetch: false,
		terminal: false,
		treeSitter: false
	}
} as const satisfies LoggerToggleTree

const LOGGER_TOGGLE_DEFAULTS = flattenTree(LOGGER_TOGGLE_TREE)

export { LOGGER_TOGGLE_DEFAULTS, LOGGER_TOGGLE_TREE }
