// This file is auto-generated by scripts/generate-logger-toggle-defaults.ts.
// Run `bun run generate:logger-toggles` to refresh it.

import { flattenTree, type LoggerToggleTree } from './flattenToggleTree'

const LOGGER_TOGGLE_TREE = {
	app: {
		$self: false,
		modal: false
	},
	'code-editor': {
		$self: false,
		'benchmark-content': false,
		clipboard: false,
		cursor: false,
		history: false,
		'horizontal-scrollbar': false,
		minimap: false,
		'minimap-render': false,
		scrollbar: false,
		trace: true,
		virtualizer: false
	},
	desktop: false,
	fs: false,
	server: false,
	web: {
		$self: false,
		focus: false,
		fsMutations: false,
		highlights: false,
		LocalDirectoryFallback: false,
		prefetch: false,
		terminal: false,
		treeSitter: false
	}
} as const satisfies LoggerToggleTree

const LOGGER_TOGGLE_DEFAULTS = flattenTree(LOGGER_TOGGLE_TREE)

export { LOGGER_TOGGLE_DEFAULTS, LOGGER_TOGGLE_TREE }
