export const LINE_HEIGHT_RATIO = 1.55
export const MIN_ESTIMATED_LINE_HEIGHT = 18
export const VERTICAL_VIRTUALIZER_OVERSCAN = 10
export const CHAR_WIDTH_RATIO = 0.65
export const COLUMN_CHARS_PER_ITEM = 80
export const HORIZONTAL_VIRTUALIZER_OVERSCAN = 6

